# Dockerfile

# Use Ubuntu as the base image
FROM ubuntu:latest

# Install vim and tcpdump
RUN apt-get update && apt-get install -y vim nano curl tcpdump python3 python3-pip

# Copy the mitm_attacker.py script from the host to the /home/ubuntu directory in the container
COPY victim_browsing.sh /home/ubuntu/victim_browsing.sh
COPY surf.glif /home/ubuntu/surf.glif

# Keep the container running
CMD ["sleep", "infinity"]
