version: '3'
services:
  victim:
    image: ubuntu:latest
    container_name: victim
    command: sleep infinity
    networks:
      - mitm_net
    cap_add:
      - NET_RAW

  attacker:
    image: ubuntu:latest
    container_name: attacker
    command: sleep infinity
    networks:
      - mitm_net
    cap_add:
      - NET_ADMIN

networks:
  mitm_net:
    driver: bridge
