version: '3'
services:
  victim:
    build:
      context: .  # The build context is still the current directory
      dockerfile: Dockerfile.victim  # Specify the custom Dockerfile for the victim
    container_name: victim
    command: sleep infinity
    networks:
      - mitm_net
    cap_add:
      - NET_RAW  # Required to manipulate network traffic

  attacker:
    build:
      context: .  # Use the current directory for the attacker as well
      dockerfile: Dockerfile.attacker  # Specify the custom Dockerfile for the attacker
    container_name: attacker
    ports:
      - "80:80"  # Map port 80 from container to host
    networks:
      - mitm_net
    cap_add:
      - NET_ADMIN  # Required to modify network settings

networks:
  mitm_net:
    driver: bridge
