# Dockerfile

# Use Ubuntu as the base image
FROM ubuntu:latest

# Install necessary tools including Apache2, vim, tcpdump, dsniff, python3, pip
RUN apt-get update && apt-get install -y vim curl nano tcpdump dsniff python3 python3-pip apache2

# Copy the mitm_attacker.py script to the home directory
COPY mitm_attacker.py /home/ubuntu/mitm_attacker.py

# Copy the fake_bank.html file to Apache's default web root directory
COPY fake_bank.html /var/www/html/fake_bank.html

# Expose port 80 for Apache2 (default HTTP port)
EXPOSE 80

# Start Apache2 in the foreground so that the container doesn't exit
CMD ["apachectl", "-D", "FOREGROUND"]

